# bonus.d/Makefile
add_file_path_comment:
	@echo python ./bonus.d/utils.d/add_file_path_comment.py ./

prompt:
	@echo bash ./bonus.d/utils.d/generate_prompt.sh -i migrations -p ./

build_tree:
	@echo bash ./bonus.d/utils.d/build_tree.sh ./
