# bonus.d/Makefile

add_file_path_comment:
	@echo python ./bonus.d/utils.d/add_file_path_comment.py ./

prompt:
	@echo bash asmo.d/bonus.d/utils.d/generate_prompt.sh -i migrations -i asmo.d -p ./ -o asmo.d/prompt_backend.txt

build_tree:
	@echo bash ./bonus.d/utils.d/build_tree.sh ./
