venv:
	@echo 'for zsh:'
	@echo 'uv venv --python 3.10 .venv_bt && source .venv_bt/bin/activate && pip install -r requirements.txt'
	@echo 'source .venv_bt/bin/activate'
	@echo ''
	@echo 'for fish:'
	@echo 'uv venv --python 3.10 .venv_bt && source .venv_bt/bin/activate.fish && pip install -r requirements.txt'
